name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
