name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --verbose

  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - run: cargo run -- carog new mypj || exit 0 # exits with 127

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: cargo clippy --all-targets --all-features -- -D clippy::all -D warnings
